# -*- coding: utf-8 -*-
"""Taller_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DKGlxx0vZRUpTLq2Sz21fghndLKeI3q
"""

#|-------------------------------------------------------------------|
#| Taller Número 4, Ejercicios de programación                       |
#| Integrantes:                                                      |
#|               - Jose Luis Rodriguez                               |
#|               - Santiago Gil Pareja                               |
#|               - Camilo Cruz Peláez                                |
#|-------------------------------------------------------------------|


#-----------------------------------------------------------------------------
#Función que permite llamar al menú while dentro del menú principal
def menu_infinito():
    import math

    #Función para operar el seno del segundo número ingresado
    def opcion_seno(numeros, cantidad):
        if cantidad >= 2:
            print(f"El seno del #2 numero ({numeros[1]}) es : {math.sin(numeros[1])}")
            print("_____________________________________________________")
            print("")
        else:
            print("se necesitan al menos 2 numeros.")

    #Función para operar la tangente del primer número ingresado
    def opcion_tangente(numeros, cantidad):
        if cantidad >= 1:
            print(f"La tangente del 1° número ({numeros[0]}) es : {math.tan(numeros[0])}")
            print("_____________________________________________________")
            print("")
        else:
            print("debe ingresar numeros primero")

    #Función para mostrar el residuo de la operacion entre el primer y segundo número
    def opcion_residuo(numeros, cantidad):
        if cantidad >= 2:
            if numeros[1] != 0:
                print(f"El residuo entre {numeros[0]} y {numeros[1]} es : {numeros[0] % numeros[1]}")
                print("_____________________________________________________")
                print("")
            else:
                print("no se puede dividir por cero")
        else:
            print("se necesitan al menos 2 números.")

    #Función para visualizar la lista de todos los números ingresados
    def opcion_imprimir(numeros, cantidad):
        if cantidad > 0:
            print("Los numeros ingresados son:")
            for i in range(cantidad):
                print(numeros[i])
        else:
            print("no hay numeros cargados.")

    #Función para visualizar cuál o cuáles números son multiplos de 3
    def opcion_multiplos3(numeros, cantidad):
        if cantidad > 0:
            hay = False
            for i in range(cantidad):
                if numeros[i] % 3 == 0:
                    print(f"{numeros[i]} es multiplo de 3")
                    hay = True
            if not hay:
                print("ninguno es multiplo de 3.")
        else:
            print("no hay numeros cargados.")

    while True:
        print("Indique la cantidad de números que desea ingresar (Mínimo 2)")
        cantidad_str = input("ingresar cantidad: ")
        if cantidad_str.isdigit():
            cantidad = int(cantidad_str)
            if cantidad >= 0:
                break
            else:
                print("La cantidad no puede ser negativa. Intenta otra vez.")
        else:
            print("Entrada inválida. Ingresa un número entero positivo.")

    numeros = [0] * cantidad
    for i in range(cantidad):
        while True:
            numero_str = input(f"ingrese el numero {i+1}: ")
            try:
                numeros[i] = float(numero_str)
                break
            except ValueError:
                print("Entrada inválida. Ingresa un número válido.")

#-------------------------------------------------------------------------
# --- Menú infinito ---
    while True:
        print("|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|")
        print("|                 Menú Operaciones                  |")
        print("|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|")
        print("|      1. mostrar seno del #2 numero                |")
        print("|      2. mostrar tangente del #1 numero            |")
        print("|      3. mostrar residuo entre el #1 y #2 numero   |")
        print("|      4. imprimir todos los numeros                |")
        print("|      5. mostrar cuales son multiplos de 3         |")
        print("|      6. Salir                                     |")
        print("|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|")
        print("")
        opcion = input("elija una opcion: ")
        print("")

        if opcion == "1":
            opcion_seno(numeros, cantidad)
        elif opcion == "2":
            opcion_tangente(numeros, cantidad)
        elif opcion == "3":
            opcion_residuo(numeros, cantidad)
        elif opcion == "4":
            opcion_imprimir(numeros, cantidad)
        elif opcion == "5":
            opcion_multiplos3(numeros, cantidad)
        elif opcion == "6":
            print("       salir del programa    ")
            break
        else:
            print(" opción no valida. intenta otra vez")

#--------------------------------------------------------------------------
#Función que permite llamar al menú de funciones dentro del menú principal
def menu_funciones():

    #Función que indica la cantidad de caracteres que conforman el mensaje ingresado
    def funcion_len():
        mensaje = (input("ingrese un mensaje: "))
        print(f"El número de caracteres del mensaje es: {len(mensaje)}")
        print("")

    #Función para operar el factorial (!) del número ingresado
    def funcion_factorial():
        import math
        print("")
        numero = int(input("ingrese un numero: "))
        print(f"El factorial del numero es: {math.factorial(numero)}")
        print("")

    #Función para hacer una suma sucesiva inciando en 1 hasta el número ingresado
    def suma_sucesivos():
      print("")
      num = int(input("Ingresa un número: "))
      suma = 0
      for i in range(1, num+1):
        suma += i
      print(f"La suma sucesiva de 1 hasta {num} es: {suma}")
      print("")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# --- Menú Funciones ---
    print("")
    print("|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|")
    print("|                 Menú Funciones                    |")
    print("|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|")
    print("|    1. Lectura cantidad de caracteres              |")
    print("|    2. Función número factorial                    |")
    print("|    3. Función suma números sucesivos              |")
    print("|    4. Opción salida                               |")
    print("|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|")
    print("")

    op = input("elija una opcion: ")

    if op == "1":
        funcion_len()
    elif op == "2":
        funcion_factorial()
    elif op == "3":
        suma_sucesivos()
    elif op == "4":
        print("       salir del programa    ")
    else:
        print(" opción no valida. intenta otra vez")

# --- Función de Menú Principal ---
def menu_principal():
    print("|---------------------------|")
    print("|~~~~~~Menú Principal~~~~~~~|")
    print("|---------------------------|")
    print("|   1). Menu ciclo While    |")
    print("|   2). Menu funciones      |")
    print("|   3). Opcion salida       |")
    print("|---------------------------|")
    print("")
    opcion = input("elija una opcion: ")
    print("")

    if opcion == "1":
        menu_infinito()
    elif opcion == "2":
        menu_funciones()
    elif opcion == "3":
        print("salir del programa")
    else:
        print(" opción no valida. intenta otra vez")
        menu_principal()


#Llama al menú principal para la interacción con el usuario
#--- Menu Principal ---
menu_principal()